# Generated by Django 3.0.5 on 2020-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDataAnnotationTask', '0002_auto_20200413_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataannotation',
            name='NumberOfAnnotations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='DataInstanceAnnotationTimes',
            field=models.IntegerField(default=1),
        ),
    ]
