# Generated by Django 3.0.5 on 2020-04-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDataAnnotationTask', '0003_auto_20200423_2345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataAnnotation',
            new_name='AnnotationDataSet',
        ),
    ]
