# Generated by Django 3.0.5 on 2020-04-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDataAnnotationTask', '0005_annotationdataset_is_viewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationdataset',
            name='who_is_viewing',
            field=models.IntegerField(default=0),
        ),
    ]
