# Generated by Django 3.0.5 on 2020-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDataAnnotationTask', '0007_auto_20200427_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataclass',
            name='ClassId',
            field=models.IntegerField(default=0),
        ),
    ]
