# Generated by Django 3.0.5 on 2020-05-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDataAnnotationTask', '0008_dataclass_classid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataclass',
            old_name='ClassId',
            new_name='ClassID',
        ),
    ]
