# Generated by Django 3.0.5 on 2020-04-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DataGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataInstance', models.CharField(max_length=400, unique=True)),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateDataGenerationTask.Task')),
            ],
        ),
    ]
