# Generated by Django 3.0.5 on 2020-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDataGenerationTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datageneration',
            name='NumberOfGenerations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='DataInstanceGenerationTimes',
            field=models.IntegerField(default=1),
        ),
    ]
