# Generated by Django 3.0.5 on 2020-04-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDataGenerationTask', '0002_auto_20200423_2345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataGeneration',
            new_name='GenerationDataSet',
        ),
    ]
