# Generated by Django 3.0.5 on 2020-05-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CreateTask', '0003_auto_20200524_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGenerationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataInstance', models.CharField(max_length=30)),
                ('GenerationResult', models.CharField(max_length=400)),
                ('UserID', models.IntegerField()),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTask.Task')),
            ],
        ),
        migrations.CreateModel(
            name='DataAnnotationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataInstance', models.CharField(max_length=30)),
                ('ClassID', models.IntegerField(default=0)),
                ('UserID', models.IntegerField()),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTask.Task')),
            ],
        ),
    ]
