# Generated by Django 3.0.5 on 2020-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataannotationresult',
            name='TaskID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datagenerationresult',
            name='TaskID',
            field=models.CharField(max_length=30),
        ),
    ]
