# Generated by Django 3.0.5 on 2020-06-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CreateDataGenerationTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGenerationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataInstance', models.CharField(max_length=30)),
                ('GenerationResult', models.CharField(max_length=400)),
                ('UserID', models.IntegerField()),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateDataGenerationTask.Task')),
            ],
        ),
    ]
