# Generated by Django 3.0.5 on 2020-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoDataGenerationTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagenerationresult',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
