# Generated by Django 3.0.5 on 2020-05-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTextDataAnnotationTask', '0001_initial'),
        ('DoTextDataAnnotationTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataannotationresult',
            name='TaskID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CreateTextDataAnnotationTask.Task'),
            preserve_default=False,
        ),
    ]
