# Generated by Django 3.0.5 on 2020-05-26 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CreateTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='no-img.jpg', upload_to='assets/images')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='none@email.com', max_length=254)),
                ('bio', models.TextField(default='')),
                ('is_contributor', models.BooleanField(default=False)),
                ('is_author', models.BooleanField(default=False)),
                ('country', models.CharField(default='', max_length=255)),
                ('field', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTask.Task')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Profile')),
            ],
        ),
    ]
