# Generated by Django 3.0.6 on 2020-06-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20200530_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatars/no-image.png', null=True, upload_to='avatars/'),
        ),
    ]
