# Generated by Django 3.0.5 on 2020-04-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_contributortask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContributorTask',
        ),
    ]
