# Generated by Django 3.0.5 on 2020-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_auto_20200501_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/avatar2.png', upload_to=''),
        ),
    ]
