# Generated by Django 3.0.5 on 2020-04-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_delete_contributortask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.IntegerField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Profile')),
            ],
        ),
    ]
