# Generated by Django 3.0.6 on 2020-06-07 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTask', '0007_merge_20200607_1649'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManagement', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributortask',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/no-image.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterUniqueTogether(
            name='contributortask',
            unique_together={('Task', 'User')},
        ),
    ]
