# Generated by Django 3.0.5 on 2020-04-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_contributortask'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributortask',
            name='is_data_annotation_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contributortask',
            name='is_data_generation_task',
            field=models.BooleanField(default=False),
        ),
    ]
