# Generated by Django 3.0.5 on 2020-05-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTask', '0003_auto_20200524_1308'),
        ('UserManagement', '0005_auto_20200425_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributortask',
            name='is_data_annotation_task',
        ),
        migrations.RemoveField(
            model_name='contributortask',
            name='is_data_generation_task',
        ),
        migrations.AlterField(
            model_name='contributortask',
            name='TaskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTask.Task'),
        ),
    ]
