# Generated by Django 3.0.5 on 2020-05-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_auto_20200524_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributortask',
            old_name='TaskID',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='contributortask',
            old_name='UserID',
            new_name='User',
        ),
    ]
