# Generated by Django 2.2.7 on 2020-05-20 06:48

import createtask.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cateogary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogaryName', models.CharField(max_length=250)),
                ('cateogaryTag', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(default='new', max_length=60)),
                ('instructions', models.CharField(max_length=1000)),
                ('taskType', models.CharField(max_length=10)),
                ('requiredNumofAnnotations', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserNew2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvFile', models.FileField(upload_to=createtask.models.directory_path)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TextDataInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.CharField(max_length=3000)),
                ('InstanceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.TextDataInstance')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='creatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.UserNew2'),
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Active', max_length=20)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Task')),
            ],
        ),
        migrations.CreateModel(
            name='MediaDataInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=createtask.models.directory_path2)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Task')),
            ],
        ),
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('questionaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Questionaire')),
            ],
        ),
        migrations.CreateModel(
            name='McqOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.McqQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleTextDataInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.AnnotationTest')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleTextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.CharField(max_length=3000)),
                ('InstanceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.ExampleTextDataInstance')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleTextAnnoResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExampleTextDataInstanceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.ExampleTextDataInstance')),
                ('resultCateogary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Cateogary')),
            ],
        ),
        migrations.CreateModel(
            name='DescrptiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('questionaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Questionaire')),
            ],
        ),
        migrations.CreateModel(
            name='CateogaryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagNumber', models.IntegerField(max_length=2)),
                ('CateogaryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Cateogary')),
            ],
        ),
        migrations.AddField(
            model_name='cateogary',
            name='taskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Task'),
        ),
        migrations.AddField(
            model_name='annotationtest',
            name='taskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Task'),
        ),
    ]
