# Generated by Django 2.2.7 on 2020-05-23 06:45

import createtask.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleMediaDataInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaData', models.FileField(upload_to=createtask.models.directory_path2)),
                ('testID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.AnnotationTest')),
            ],
        ),
        migrations.CreateModel(
            name='TextAnnoAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerCateogary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Cateogary')),
                ('textInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.ExampleTextDataInstance')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.UserNew2')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('annotatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.UserNew2')),
                ('testID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.AnnotationTest')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAnnoAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerCateogary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Cateogary')),
                ('mediaInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.ExampleMediaDataInstance')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.UserNew2')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleMediaAnnoResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExampleMediaDataInstanceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.ExampleMediaDataInstance')),
                ('resultCateogary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Cateogary')),
            ],
        ),
    ]
