# Generated by Django 3.0.5 on 2020-04-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNew2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='annotationtask',
            name='creatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.UserNew2'),
        ),
        # migrations.DeleteModel(
        #     name='UserNew1',
        # ),
    ]
