# Generated by Django 3.0.5 on 2020-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadatainstance',
            name='LastUpdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='textdatainstance',
            name='LastUpdate',
            field=models.DateTimeField(),
        ),
    ]
