# Generated by Django 2.2.7 on 2020-05-31 05:16

import CreateTask.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTask', '0002_auto_20200526_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenTextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvFile', models.FileField(upload_to=CreateTask.models.directory_path)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTask.Task')),
            ],
        ),
        migrations.CreateModel(
            name='DataGenTextInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=5000)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTask.Task')),
            ],
        ),
    ]
