# Generated by Django 3.0.5 on 2020-04-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0002_auto_20200411_1804'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='UserNew1',
        # ),
        migrations.RenameField(
            model_name='annotationtask',
            old_name='decription',
            new_name='description',
        ),
    ]
