# Generated by Django 2.2.7 on 2020-05-29 03:12

import createtask.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0002_examplemediaannoresult_examplemediadatainstance_mediaannoanswers_testresult_textannoanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemediadatainstance',
            name='mediaData',
            field=models.FileField(upload_to=createtask.models.directory_path3),
        ),
        migrations.CreateModel(
            name='GenTextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvFile', models.FileField(upload_to=createtask.models.directory_path)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Task')),
            ],
        ),
        migrations.CreateModel(
            name='DataGenTextInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=5000)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Task')),
            ],
        ),
    ]
