# Generated by Django 2.2.7 on 2020-05-31 08:42

import CreateTask.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTask', '0003_datagentextinstance_gentextfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtest',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TestTextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvFile', models.FileField(upload_to=CreateTask.models.directory_path5)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTask.Task')),
            ],
        ),
    ]
