# Generated by Django 2.2.7 on 2020-04-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0004_auto_20200412_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescrptiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='McqOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Active', max_length=20)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.AnnotationTask')),
            ],
        ),
        # migrations.DeleteModel(
        #     name='UserNew1',
        # ),
        migrations.AddField(
            model_name='mcqquestion',
            name='questionaireID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Questionaire'),
        ),
        migrations.AddField(
            model_name='mcqoption',
            name='questionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.McqQuestion'),
        ),
        migrations.AddField(
            model_name='descrptivequestion',
            name='questionaireID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.Questionaire'),
        ),
    ]
