# Generated by Django 2.2.7 on 2020-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTask', '0004_auto_20200531_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationtest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
