# Generated by Django 2.2.7 on 2020-06-05 09:16

import CreateTask.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTask', '0005_auto_20200531_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtest',
            name='required_marks',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='examplemediadatainstance',
            name='mediaData',
            field=models.FileField(upload_to=CreateTask.models.directory_path3),
        ),
    ]
