# Generated by Django 2.2.7 on 2020-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0005_auto_20200413_1245'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='UserNew1',
        # ),
        migrations.AddField(
            model_name='mcqoption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
