# Generated by Django 3.0.6 on 2020-06-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTask', '0006_auto_20200605_1446'),
        ('CreateTask', '0003_auto_20200601_1835'),
    ]

    operations = [
    ]
