# Generated by Django 2.2.7 on 2020-05-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0006_auto_20200413_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classtitle', models.CharField(max_length=1000)),
                ('requiredDataType', models.CharField(default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationExamplesText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=2000)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.GenerationClass')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(default='new', max_length=60)),
                ('instructions', models.CharField(max_length=1000)),
                ('creatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.UserNew2')),
            ],
        ),
        # migrations.DeleteModel(
        #     name='UserNew1',
        # ),
        migrations.AddField(
            model_name='generationclass',
            name='TaskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.GenerationTask'),
        ),
    ]
