# Generated by Django 2.2.7 on 2020-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTask', '0007_merge_20200607_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='inprogress', max_length=60),
        ),
    ]
