# Generated by Django 2.2.7 on 2020-05-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0007_auto_20200501_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnnotationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(default='new', max_length=60)),
                ('instructions', models.CharField(max_length=1000)),
                ('csvFile', models.FileField(upload_to='new')),
                ('creatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.UserNew2')),
            ],
        ),
        migrations.CreateModel(
            name='TextCateogary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogaryName', models.CharField(max_length=250)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.TextAnnotationTask')),
            ],
        ),
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='TextDataInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.TextAnnotationTask')),
            ],
        ),
        # migrations.DeleteModel(
        #     name='UserNew1',
        # ),
        migrations.AddField(
            model_name='textdata',
            name='InstanceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.TextDataInstance'),
        ),
    ]
