# Generated by Django 2.2.7 on 2020-05-08 03:40

import createtask.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0008_auto_20200507_2058'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='UserNew1',
        # ),
        migrations.AlterField(
            model_name='textannotationtask',
            name='csvFile',
            field=models.FileField(upload_to=createtask.models.directory_path),
        ),
    ]
