# Generated by Django 2.2.7 on 2020-05-08 03:56

import createtask.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0009_auto_20200508_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvFile', models.FileField(upload_to=createtask.models.directory_path)),
            ],
        ),
        # migrations.DeleteModel(
        #     name='UserNew1',
        # ),
        migrations.RemoveField(
            model_name='textannotationtask',
            name='csvFile',
        ),
        migrations.AddField(
            model_name='textfile',
            name='taskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.TextAnnotationTask'),
        ),
    ]
