# Generated by Django 2.2.7 on 2020-05-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0010_auto_20200508_0926'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='UserNew1',
        # ),
    ]
