# Generated by Django 2.2.7 on 2020-05-13 07:48

import createtask.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createtask', '0011_delete_usernew1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=createtask.models.directory_path2)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createtask.AnnotationTask')),
            ],
        ),
        # migrations.DeleteModel(
        #     name='UserNew1',
        # ),
    ]
