# Generated by Django 3.0.5 on 2020-06-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testresultrank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='annotatorID',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='testID',
        ),
        migrations.DeleteModel(
            name='AnnotationTest',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
        migrations.DeleteModel(
            name='User1',
        ),
    ]
