# Generated by Django 3.0.5 on 2020-04-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoDataAnnotationTask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataannotationresult',
            old_name='TaskId',
            new_name='TaskID',
        ),
    ]
