# Generated by Django 3.0.5 on 2020-06-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTask', '0002_auto_20200526_2055'),
        ('DoDataAnnotationTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataannotationresult',
            name='DataInstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTask.MediaDataInstance'),
        ),
    ]
