# Generated by Django 3.0.5 on 2020-04-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDataAnnotationTask', '0001_initial'),
        ('DoDataAnnotationTask', '0003_auto_20200413_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataannotationresult',
            name='ClassName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateDataAnnotationTask.DataClass'),
        ),
    ]
