# Generated by Django 3.0.5 on 2020-04-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoDataAnnotationTask', '0005_auto_20200413_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataannotationresult',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
