# Generated by Django 3.0.5 on 2020-05-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoDataAnnotationTask', '0006_dataannotationresult_lastupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataannotationresult',
            name='ClassName',
        ),
        migrations.AddField(
            model_name='dataannotationresult',
            name='ClassId',
            field=models.IntegerField(default=0),
        ),
    ]
