# Generated by Django 3.0.5 on 2020-05-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoDataAnnotationTask', '0007_auto_20200507_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataannotationresult',
            old_name='ClassId',
            new_name='ClassID',
        ),
    ]
