# Generated by Django 3.0.5 on 2020-06-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextDataAnalyse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationdatasetresult',
            name='Datainstance',
        ),
        migrations.RemoveField(
            model_name='annotationdatasetresult',
            name='TaskID',
        ),
        migrations.RemoveField(
            model_name='dataclass',
            name='TaskID',
        ),
        migrations.DeleteModel(
            name='AnnotationDataSet',
        ),
        migrations.DeleteModel(
            name='AnnotationDataSetresult',
        ),
        migrations.DeleteModel(
            name='DataClass',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
